# Site
repository: JingMatrix/cv
favicon: images/favicon.ico

# Personal info
name: Jianyu MA
title: PhD in mathematics, expert in Android security and open-source developer
email: jingmatrix@gmail.com
# phone: Your phone number (optional)
website: https://www.math.univ-toulouse.fr/~jma/

# Social links
# twitter_username: jekyllrb
github_username:  JingMatrix
stackexchange_username: "458137"
# dribbble_username: jekyll
facebook_username: jianyu.ma.796
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# youtube_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
about_title: About Me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
  I am a [PhD in mathematics](https://www.math.univ-toulouse.fr/~jma/pdf/thesis.pdf) and I am currently teaching in university at Toulouse, France.

  I was born on October 26th, 1998. However, you may already know that many Chinese people use a different [calendar](https://en.wikipedia.org/wiki/Chinese_calendar), so my birthday 🎂 'changes' every year.

  I enjoy writing, in English, French and Chinese. There is a language switch button in [my blog](https://jingmatrix.github.io/) to see different contents.
  - [English](https://jingmatrix.github.io/en/): math notes, programming tricks, dairies
  - [French](https://jingmatrix.github.io/fr/): poems, life in France
  - [Chinese](https://jingmatrix.github.io/zh/): thoughts, poems

  Using Google Drive, I share [Math books](https://drive.google.com/drive/folders/1O279emuW9Z1LGmQ94fbRYfjZoxT8bpwU) and other [Hobby readings](https://drive.google.com/drive/folders/1-5uxWOntIKyiwtsKfaKgsxlCYe6cFVFX); books there are well-compressed and include bookmarks (manually embedded).

  In a sense, my taste is a bit retro:
    - For musician 🎶, I prefer [Beethoven](https://fr.wikipedia.org/wiki/Ludwig_van_Beethoven).
    - For director 🎥, I prefer [Béla Tarr](https://fr.wikipedia.org/wiki/B%C3%A9la_Tarr), all of his movies are Black-and-White.
    - For writer 📘, I prefer [Nietzsche](https://en.wikipedia.org/wiki/Friedrich_Nietzsche), especially his [Par-delà le bien et le mal](https://fr.wikipedia.org/wiki/Par-del%C3%A0_le_bien_et_le_mal).

    Current page is **archived**, and only serves to provide more details of my life before PhD.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jemoji
